import { Nunito } from 'next/font/google'
import './globals.css'
import Header from './components/Header';

const nunito = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Portafolio  Benjamin L.',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='!scroll-smooth' >
      <body className={nunito.className}>
        <div>
        <Header/>     
        </div>
        {children}
      </body>
    </html>
  )
}
